//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 04:54:07 PM GMT+08:00 
//


package com.hybris.fortress.gensrc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="AttName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AttValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeType", propOrder = {

})
public class AttributeType {

    @XmlElement(name = "AttName", required = true)
    protected String attName;
    @XmlElement(name = "AttValue", required = true)
    protected String attValue;

    /**
     * Gets the value of the attName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttName() {
        return attName;
    }

    /**
     * Sets the value of the attName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttName(String value) {
        this.attName = value;
    }

    /**
     * Gets the value of the attValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttValue() {
        return attValue;
    }

    /**
     * Sets the value of the attValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttValue(String value) {
        this.attValue = value;
    }

}
