//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 04:54:07 PM GMT+08:00 
//


package com.hybris.fortress.gensrc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChildType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChildType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ChildID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChildBirthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChildFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChildGender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChildType", propOrder = {

})
public class ChildType {

    @XmlElement(name = "ChildID")
    protected String childID;
    @XmlElement(name = "ChildBirthDate")
    protected String childBirthDate;
    @XmlElement(name = "ChildFirstName")
    protected String childFirstName;
    @XmlElement(name = "ChildGender")
    protected String childGender;

    /**
     * Gets the value of the childID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildID() {
        return childID;
    }

    /**
     * Sets the value of the childID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildID(String value) {
        this.childID = value;
    }

    /**
     * Gets the value of the childBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildBirthDate() {
        return childBirthDate;
    }

    /**
     * Sets the value of the childBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildBirthDate(String value) {
        this.childBirthDate = value;
    }

    /**
     * Gets the value of the childFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildFirstName() {
        return childFirstName;
    }

    /**
     * Sets the value of the childFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildFirstName(String value) {
        this.childFirstName = value;
    }

    /**
     * Gets the value of the childGender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildGender() {
        return childGender;
    }

    /**
     * Sets the value of the childGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildGender(String value) {
        this.childGender = value;
    }

}
