//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 04:54:07 PM GMT+08:00 
//


package com.hybris.fortress.gensrc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConAttrib complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConAttrib">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CAttName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CAttValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CActiveFlag" type="{}BooleanType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConAttrib", propOrder = {
    "cAttName",
    "cAttValue",
    "cActiveFlag"
})
public class ConAttrib {

    @XmlElement(name = "CAttName")
    protected String cAttName;
    @XmlElement(name = "CAttValue")
    protected String cAttValue;
    @XmlElement(name = "CActiveFlag")
    protected String cActiveFlag;

    /**
     * Gets the value of the cAttName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAttName() {
        return cAttName;
    }

    /**
     * Sets the value of the cAttName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAttName(String value) {
        this.cAttName = value;
    }

    /**
     * Gets the value of the cAttValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAttValue() {
        return cAttValue;
    }

    /**
     * Sets the value of the cAttValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAttValue(String value) {
        this.cAttValue = value;
    }

    /**
     * Gets the value of the cActiveFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCActiveFlag() {
        return cActiveFlag;
    }

    /**
     * Sets the value of the cActiveFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCActiveFlag(String value) {
        this.cActiveFlag = value;
    }

}
