//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 04:54:07 PM GMT+08:00 
//


package com.hybris.fortress.gensrc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SuppressFTRSMS" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressFTREmail" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressFTRDM" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressPNSSMS" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressPNSEmail" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressPNSDM" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressWTCSMS" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressWTCEmail" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="SuppressWTCDM" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="Occupation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactType", propOrder = {
    "suppressFTRSMS",
    "suppressFTREmail",
    "suppressFTRDM",
    "suppressPNSSMS",
    "suppressPNSEmail",
    "suppressPNSDM",
    "suppressWTCSMS",
    "suppressWTCEmail",
    "suppressWTCDM",
    "occupation"
})
public class ContactType {

    @XmlElement(name = "SuppressFTRSMS")
    protected String suppressFTRSMS;
    @XmlElement(name = "SuppressFTREmail")
    protected String suppressFTREmail;
    @XmlElement(name = "SuppressFTRDM")
    protected String suppressFTRDM;
    @XmlElement(name = "SuppressPNSSMS")
    protected String suppressPNSSMS;
    @XmlElement(name = "SuppressPNSEmail")
    protected String suppressPNSEmail;
    @XmlElement(name = "SuppressPNSDM")
    protected String suppressPNSDM;
    @XmlElement(name = "SuppressWTCSMS")
    protected String suppressWTCSMS;
    @XmlElement(name = "SuppressWTCEmail")
    protected String suppressWTCEmail;
    @XmlElement(name = "SuppressWTCDM")
    protected String suppressWTCDM;
    @XmlElement(name = "Occupation")
    protected String occupation;

    /**
     * Gets the value of the suppressFTRSMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressFTRSMS() {
        return suppressFTRSMS;
    }

    /**
     * Sets the value of the suppressFTRSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressFTRSMS(String value) {
        this.suppressFTRSMS = value;
    }

    /**
     * Gets the value of the suppressFTREmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressFTREmail() {
        return suppressFTREmail;
    }

    /**
     * Sets the value of the suppressFTREmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressFTREmail(String value) {
        this.suppressFTREmail = value;
    }

    /**
     * Gets the value of the suppressFTRDM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressFTRDM() {
        return suppressFTRDM;
    }

    /**
     * Sets the value of the suppressFTRDM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressFTRDM(String value) {
        this.suppressFTRDM = value;
    }

    /**
     * Gets the value of the suppressPNSSMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressPNSSMS() {
        return suppressPNSSMS;
    }

    /**
     * Sets the value of the suppressPNSSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressPNSSMS(String value) {
        this.suppressPNSSMS = value;
    }

    /**
     * Gets the value of the suppressPNSEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressPNSEmail() {
        return suppressPNSEmail;
    }

    /**
     * Sets the value of the suppressPNSEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressPNSEmail(String value) {
        this.suppressPNSEmail = value;
    }

    /**
     * Gets the value of the suppressPNSDM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressPNSDM() {
        return suppressPNSDM;
    }

    /**
     * Sets the value of the suppressPNSDM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressPNSDM(String value) {
        this.suppressPNSDM = value;
    }

    /**
     * Gets the value of the suppressWTCSMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressWTCSMS() {
        return suppressWTCSMS;
    }

    /**
     * Sets the value of the suppressWTCSMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressWTCSMS(String value) {
        this.suppressWTCSMS = value;
    }

    /**
     * Gets the value of the suppressWTCEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressWTCEmail() {
        return suppressWTCEmail;
    }

    /**
     * Sets the value of the suppressWTCEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressWTCEmail(String value) {
        this.suppressWTCEmail = value;
    }

    /**
     * Gets the value of the suppressWTCDM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressWTCDM() {
        return suppressWTCDM;
    }

    /**
     * Sets the value of the suppressWTCDM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressWTCDM(String value) {
        this.suppressWTCDM = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

}
