//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 04:54:07 PM GMT+08:00 
//


package com.hybris.fortress.gensrc;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MemberNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExternalCustomerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PersonalTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="JobTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmployeeFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="EmployeeNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PersonalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Gender" type="{}NillableGenderType" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BirthDate" type="{}NillableSiebelDateType" minOccurs="0"/>
 *         &lt;element name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PointValue" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="GoldCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLine7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ZipcodeExt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Town" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="District" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MetroArea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CrossStreet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="County" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Province" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressInvalidFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MobilePhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BlockedFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="InactiveFlag" type="{}NillableBooleanType" minOccurs="0"/>
 *         &lt;element name="AnonymousFlag" type="{}NillableBooleanType" minOccurs="0"/>
 *         &lt;element name="ExternMailFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="ExternEmailFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="ExternSmsFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="InternMailFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="InternEmailFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="InternSmsFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="PrivacyAgreeFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="ReceivePromotionFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="IntialMailFlag" type="{}NillableBooleanType" minOccurs="0"/>
 *         &lt;element name="MailVerificationFlag" type="{}NillableBooleanType" minOccurs="0"/>
 *         &lt;element name="LanguageCode" type="{}NillableLanguageCodeType" minOccurs="0"/>
 *         &lt;element name="VatNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IssuedStore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PointsReconciled" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="PointsWaiting" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="StartDate" type="{}NillableSiebelDateTimeType" minOccurs="0"/>
 *         &lt;element name="AccrualStartDate" type="{}NillableSiebelDateType" minOccurs="0"/>
 *         &lt;element name="LastUpdatedDate" type="{}NillableSiebelDateType" minOccurs="0"/>
 *         &lt;element name="EnrollmentChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActivationChannel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApprovalDate" type="{}NillableSiebelDateType" minOccurs="0"/>
 *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SalesValueToGetCheque" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="PointsToGetCheque" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="LastAccrualTxnDate" type="{}NillableSiebelDateType" minOccurs="0"/>
 *         &lt;element name="Pareto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ParetoTendency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastTxnDate" type="{}NillableSiebelDateType" minOccurs="0"/>
 *         &lt;element name="LastRedemptionDate" type="{}NillableSiebelDateType" minOccurs="0"/>
 *         &lt;element name="ChildNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PersonalIncome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HouseholdIncome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PassportNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherLanguageLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OtherLanguageFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Education" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Occupation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Race" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrefCommMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MemberStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MemberSubStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReceivePartnerPromotionFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="Segments" type="{}SegmentsType"/>
 *         &lt;element name="Attributes" type="{}AttributesType"/>
 *         &lt;element name="Children" type="{}ChildrenType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerType", propOrder = {
    "memberNumber",
    "cardNumber",
    "externalCustomerId",
    "personalTitle",
    "jobTitle",
    "employeeFlag",
    "employeeNumber",
    "personalID",
    "gender",
    "lastName",
    "middleName",
    "firstName",
    "birthDate",
    "maritalStatus",
    "pointValue",
    "goldCode",
    "addressNumber",
    "addressLine",
    "addressLine2",
    "addressLine3",
    "addressLine4",
    "addressLine5",
    "addressLine6",
    "addressLine7",
    "zipCode",
    "zipcodeExt",
    "town",
    "district",
    "metroArea",
    "crossStreet",
    "county",
    "province",
    "state",
    "country",
    "addressInvalidFlag",
    "email",
    "phone",
    "mobilePhone",
    "blockedFlag",
    "inactiveFlag",
    "anonymousFlag",
    "externMailFlag",
    "externEmailFlag",
    "externSmsFlag",
    "internMailFlag",
    "internEmailFlag",
    "internSmsFlag",
    "privacyAgreeFlag",
    "receivePromotionFlag",
    "intialMailFlag",
    "mailVerificationFlag",
    "languageCode",
    "vatNumber",
    "issuedStore",
    "pointsReconciled",
    "pointsWaiting",
    "startDate",
    "accrualStartDate",
    "lastUpdatedDate",
    "enrollmentChannel",
    "activationChannel",
    "approvalDate",
    "currencyCode",
    "salesValueToGetCheque",
    "pointsToGetCheque",
    "lastAccrualTxnDate",
    "pareto",
    "paretoTendency",
    "cardType",
    "lastTxnDate",
    "lastRedemptionDate",
    "childNum",
    "personalIncome",
    "householdIncome",
    "passportNumber",
    "otherLanguageLastName",
    "otherLanguageFirstName",
    "education",
    "occupation",
    "race",
    "prefCommMethod",
    "memberStatus",
    "memberSubStatus",
    "cardStatus",
    "receivePartnerPromotionFlag",
    "segments",
    "attributes",
    "children"
})
@XmlSeeAlso({
    FtrCustomerType.class
})
public class CustomerType {

    @XmlElement(name = "MemberNumber")
    protected String memberNumber;
    @XmlElement(name = "CardNumber")
    protected String cardNumber;
    @XmlElement(name = "ExternalCustomerId")
    protected String externalCustomerId;
    @XmlElement(name = "PersonalTitle")
    protected String personalTitle;
    @XmlElement(name = "JobTitle")
    protected String jobTitle;
    @XmlElement(name = "EmployeeFlag")
    protected String employeeFlag;
    @XmlElement(name = "EmployeeNumber")
    protected String employeeNumber;
    @XmlElement(name = "PersonalID")
    protected String personalID;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "BirthDate")
    protected String birthDate;
    @XmlElement(name = "MaritalStatus")
    protected String maritalStatus;
    @XmlElement(name = "PointValue")
    protected BigInteger pointValue;
    @XmlElement(name = "GoldCode")
    protected String goldCode;
    @XmlElement(name = "AddressNumber")
    protected String addressNumber;
    @XmlElement(name = "AddressLine")
    protected String addressLine;
    @XmlElement(name = "AddressLine2")
    protected String addressLine2;
    @XmlElement(name = "AddressLine3")
    protected String addressLine3;
    @XmlElement(name = "AddressLine4")
    protected String addressLine4;
    @XmlElement(name = "AddressLine5")
    protected String addressLine5;
    @XmlElement(name = "AddressLine6")
    protected String addressLine6;
    @XmlElement(name = "AddressLine7")
    protected String addressLine7;
    @XmlElement(name = "ZipCode")
    protected String zipCode;
    @XmlElement(name = "ZipcodeExt")
    protected String zipcodeExt;
    @XmlElement(name = "Town")
    protected String town;
    @XmlElement(name = "District")
    protected String district;
    @XmlElement(name = "MetroArea")
    protected String metroArea;
    @XmlElement(name = "CrossStreet")
    protected String crossStreet;
    @XmlElement(name = "County")
    protected String county;
    @XmlElement(name = "Province")
    protected String province;
    @XmlElement(name = "State")
    protected String state;
    @XmlElement(name = "Country")
    protected String country;
    @XmlElement(name = "AddressInvalidFlag")
    protected String addressInvalidFlag;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "Phone")
    protected String phone;
    @XmlElement(name = "MobilePhone")
    protected String mobilePhone;
    @XmlElement(name = "BlockedFlag")
    protected String blockedFlag;
    @XmlElement(name = "InactiveFlag")
    protected String inactiveFlag;
    @XmlElement(name = "AnonymousFlag")
    protected String anonymousFlag;
    @XmlElement(name = "ExternMailFlag")
    protected String externMailFlag;
    @XmlElement(name = "ExternEmailFlag")
    protected String externEmailFlag;
    @XmlElement(name = "ExternSmsFlag")
    protected String externSmsFlag;
    @XmlElement(name = "InternMailFlag")
    protected String internMailFlag;
    @XmlElement(name = "InternEmailFlag")
    protected String internEmailFlag;
    @XmlElement(name = "InternSmsFlag")
    protected String internSmsFlag;
    @XmlElement(name = "PrivacyAgreeFlag")
    protected String privacyAgreeFlag;
    @XmlElement(name = "ReceivePromotionFlag")
    protected String receivePromotionFlag;
    @XmlElement(name = "IntialMailFlag")
    protected String intialMailFlag;
    @XmlElement(name = "MailVerificationFlag")
    protected String mailVerificationFlag;
    @XmlElement(name = "LanguageCode")
    protected String languageCode;
    @XmlElement(name = "VatNumber")
    protected String vatNumber;
    @XmlElement(name = "IssuedStore")
    protected String issuedStore;
    @XmlElement(name = "PointsReconciled")
    protected BigInteger pointsReconciled;
    @XmlElement(name = "PointsWaiting")
    protected BigInteger pointsWaiting;
    @XmlElement(name = "StartDate")
    protected String startDate;
    @XmlElement(name = "AccrualStartDate")
    protected String accrualStartDate;
    @XmlElement(name = "LastUpdatedDate")
    protected String lastUpdatedDate;
    @XmlElement(name = "EnrollmentChannel")
    protected String enrollmentChannel;
    @XmlElement(name = "ActivationChannel")
    protected String activationChannel;
    @XmlElement(name = "ApprovalDate")
    protected String approvalDate;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "SalesValueToGetCheque")
    protected Float salesValueToGetCheque;
    @XmlElement(name = "PointsToGetCheque")
    protected BigDecimal pointsToGetCheque;
    @XmlElement(name = "LastAccrualTxnDate")
    protected String lastAccrualTxnDate;
    @XmlElement(name = "Pareto")
    protected String pareto;
    @XmlElement(name = "ParetoTendency")
    protected String paretoTendency;
    @XmlElement(name = "CardType")
    protected String cardType;
    @XmlElement(name = "LastTxnDate")
    protected String lastTxnDate;
    @XmlElement(name = "LastRedemptionDate")
    protected String lastRedemptionDate;
    @XmlElement(name = "ChildNum")
    protected String childNum;
    @XmlElement(name = "PersonalIncome")
    protected String personalIncome;
    @XmlElement(name = "HouseholdIncome")
    protected String householdIncome;
    @XmlElement(name = "PassportNumber")
    protected String passportNumber;
    @XmlElement(name = "OtherLanguageLastName")
    protected String otherLanguageLastName;
    @XmlElement(name = "OtherLanguageFirstName")
    protected String otherLanguageFirstName;
    @XmlElement(name = "Education")
    protected String education;
    @XmlElement(name = "Occupation")
    protected String occupation;
    @XmlElement(name = "Race")
    protected String race;
    @XmlElement(name = "PrefCommMethod")
    protected String prefCommMethod;
    @XmlElement(name = "MemberStatus")
    protected String memberStatus;
    @XmlElement(name = "MemberSubStatus")
    protected String memberSubStatus;
    @XmlElement(name = "CardStatus")
    protected String cardStatus;
    @XmlElement(name = "ReceivePartnerPromotionFlag")
    protected String receivePartnerPromotionFlag;
    @XmlElement(name = "Segments", required = true)
    protected SegmentsType segments;
    @XmlElement(name = "Attributes", required = true)
    protected AttributesType attributes;
    @XmlElement(name = "Children", required = true)
    protected ChildrenType children;

    /**
     * Gets the value of the memberNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberNumber() {
        return memberNumber;
    }

    /**
     * Sets the value of the memberNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberNumber(String value) {
        this.memberNumber = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the externalCustomerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalCustomerId() {
        return externalCustomerId;
    }

    /**
     * Sets the value of the externalCustomerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalCustomerId(String value) {
        this.externalCustomerId = value;
    }

    /**
     * Gets the value of the personalTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalTitle() {
        return personalTitle;
    }

    /**
     * Sets the value of the personalTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalTitle(String value) {
        this.personalTitle = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the employeeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeFlag() {
        return employeeFlag;
    }

    /**
     * Sets the value of the employeeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeFlag(String value) {
        this.employeeFlag = value;
    }

    /**
     * Gets the value of the employeeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeNumber() {
        return employeeNumber;
    }

    /**
     * Sets the value of the employeeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeNumber(String value) {
        this.employeeNumber = value;
    }

    /**
     * Gets the value of the personalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalID() {
        return personalID;
    }

    /**
     * Sets the value of the personalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalID(String value) {
        this.personalID = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the pointValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPointValue() {
        return pointValue;
    }

    /**
     * Sets the value of the pointValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPointValue(BigInteger value) {
        this.pointValue = value;
    }

    /**
     * Gets the value of the goldCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoldCode() {
        return goldCode;
    }

    /**
     * Sets the value of the goldCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoldCode(String value) {
        this.goldCode = value;
    }

    /**
     * Gets the value of the addressNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressNumber() {
        return addressNumber;
    }

    /**
     * Sets the value of the addressNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressNumber(String value) {
        this.addressNumber = value;
    }

    /**
     * Gets the value of the addressLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine() {
        return addressLine;
    }

    /**
     * Sets the value of the addressLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine(String value) {
        this.addressLine = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the addressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine3() {
        return addressLine3;
    }

    /**
     * Sets the value of the addressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine3(String value) {
        this.addressLine3 = value;
    }

    /**
     * Gets the value of the addressLine4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine4() {
        return addressLine4;
    }

    /**
     * Sets the value of the addressLine4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine4(String value) {
        this.addressLine4 = value;
    }

    /**
     * Gets the value of the addressLine5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine5() {
        return addressLine5;
    }

    /**
     * Sets the value of the addressLine5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine5(String value) {
        this.addressLine5 = value;
    }

    /**
     * Gets the value of the addressLine6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine6() {
        return addressLine6;
    }

    /**
     * Sets the value of the addressLine6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine6(String value) {
        this.addressLine6 = value;
    }

    /**
     * Gets the value of the addressLine7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine7() {
        return addressLine7;
    }

    /**
     * Sets the value of the addressLine7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine7(String value) {
        this.addressLine7 = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the zipcodeExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipcodeExt() {
        return zipcodeExt;
    }

    /**
     * Sets the value of the zipcodeExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipcodeExt(String value) {
        this.zipcodeExt = value;
    }

    /**
     * Gets the value of the town property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTown() {
        return town;
    }

    /**
     * Sets the value of the town property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTown(String value) {
        this.town = value;
    }

    /**
     * Gets the value of the district property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistrict() {
        return district;
    }

    /**
     * Sets the value of the district property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistrict(String value) {
        this.district = value;
    }

    /**
     * Gets the value of the metroArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetroArea() {
        return metroArea;
    }

    /**
     * Sets the value of the metroArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetroArea(String value) {
        this.metroArea = value;
    }

    /**
     * Gets the value of the crossStreet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrossStreet() {
        return crossStreet;
    }

    /**
     * Sets the value of the crossStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrossStreet(String value) {
        this.crossStreet = value;
    }

    /**
     * Gets the value of the county property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCounty() {
        return county;
    }

    /**
     * Sets the value of the county property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounty(String value) {
        this.county = value;
    }

    /**
     * Gets the value of the province property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvince() {
        return province;
    }

    /**
     * Sets the value of the province property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvince(String value) {
        this.province = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the addressInvalidFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressInvalidFlag() {
        return addressInvalidFlag;
    }

    /**
     * Sets the value of the addressInvalidFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressInvalidFlag(String value) {
        this.addressInvalidFlag = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the mobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * Sets the value of the mobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhone(String value) {
        this.mobilePhone = value;
    }

    /**
     * Gets the value of the blockedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlockedFlag() {
        return blockedFlag;
    }

    /**
     * Sets the value of the blockedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlockedFlag(String value) {
        this.blockedFlag = value;
    }

    /**
     * Gets the value of the inactiveFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInactiveFlag() {
        return inactiveFlag;
    }

    /**
     * Sets the value of the inactiveFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInactiveFlag(String value) {
        this.inactiveFlag = value;
    }

    /**
     * Gets the value of the anonymousFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnonymousFlag() {
        return anonymousFlag;
    }

    /**
     * Sets the value of the anonymousFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnonymousFlag(String value) {
        this.anonymousFlag = value;
    }

    /**
     * Gets the value of the externMailFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternMailFlag() {
        return externMailFlag;
    }

    /**
     * Sets the value of the externMailFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternMailFlag(String value) {
        this.externMailFlag = value;
    }

    /**
     * Gets the value of the externEmailFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternEmailFlag() {
        return externEmailFlag;
    }

    /**
     * Sets the value of the externEmailFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternEmailFlag(String value) {
        this.externEmailFlag = value;
    }

    /**
     * Gets the value of the externSmsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternSmsFlag() {
        return externSmsFlag;
    }

    /**
     * Sets the value of the externSmsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternSmsFlag(String value) {
        this.externSmsFlag = value;
    }

    /**
     * Gets the value of the internMailFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternMailFlag() {
        return internMailFlag;
    }

    /**
     * Sets the value of the internMailFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternMailFlag(String value) {
        this.internMailFlag = value;
    }

    /**
     * Gets the value of the internEmailFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternEmailFlag() {
        return internEmailFlag;
    }

    /**
     * Sets the value of the internEmailFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternEmailFlag(String value) {
        this.internEmailFlag = value;
    }

    /**
     * Gets the value of the internSmsFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternSmsFlag() {
        return internSmsFlag;
    }

    /**
     * Sets the value of the internSmsFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternSmsFlag(String value) {
        this.internSmsFlag = value;
    }

    /**
     * Gets the value of the privacyAgreeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacyAgreeFlag() {
        return privacyAgreeFlag;
    }

    /**
     * Sets the value of the privacyAgreeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacyAgreeFlag(String value) {
        this.privacyAgreeFlag = value;
    }

    /**
     * Gets the value of the receivePromotionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivePromotionFlag() {
        return receivePromotionFlag;
    }

    /**
     * Sets the value of the receivePromotionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivePromotionFlag(String value) {
        this.receivePromotionFlag = value;
    }

    /**
     * Gets the value of the intialMailFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntialMailFlag() {
        return intialMailFlag;
    }

    /**
     * Sets the value of the intialMailFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntialMailFlag(String value) {
        this.intialMailFlag = value;
    }

    /**
     * Gets the value of the mailVerificationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailVerificationFlag() {
        return mailVerificationFlag;
    }

    /**
     * Sets the value of the mailVerificationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailVerificationFlag(String value) {
        this.mailVerificationFlag = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageCode(String value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the vatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVatNumber() {
        return vatNumber;
    }

    /**
     * Sets the value of the vatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVatNumber(String value) {
        this.vatNumber = value;
    }

    /**
     * Gets the value of the issuedStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuedStore() {
        return issuedStore;
    }

    /**
     * Sets the value of the issuedStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuedStore(String value) {
        this.issuedStore = value;
    }

    /**
     * Gets the value of the pointsReconciled property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPointsReconciled() {
        return pointsReconciled;
    }

    /**
     * Sets the value of the pointsReconciled property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPointsReconciled(BigInteger value) {
        this.pointsReconciled = value;
    }

    /**
     * Gets the value of the pointsWaiting property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPointsWaiting() {
        return pointsWaiting;
    }

    /**
     * Sets the value of the pointsWaiting property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPointsWaiting(BigInteger value) {
        this.pointsWaiting = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the accrualStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccrualStartDate() {
        return accrualStartDate;
    }

    /**
     * Sets the value of the accrualStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccrualStartDate(String value) {
        this.accrualStartDate = value;
    }

    /**
     * Gets the value of the lastUpdatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * Sets the value of the lastUpdatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdatedDate(String value) {
        this.lastUpdatedDate = value;
    }

    /**
     * Gets the value of the enrollmentChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentChannel() {
        return enrollmentChannel;
    }

    /**
     * Sets the value of the enrollmentChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentChannel(String value) {
        this.enrollmentChannel = value;
    }

    /**
     * Gets the value of the activationChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationChannel() {
        return activationChannel;
    }

    /**
     * Sets the value of the activationChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationChannel(String value) {
        this.activationChannel = value;
    }

    /**
     * Gets the value of the approvalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalDate() {
        return approvalDate;
    }

    /**
     * Sets the value of the approvalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalDate(String value) {
        this.approvalDate = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the salesValueToGetCheque property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSalesValueToGetCheque() {
        return salesValueToGetCheque;
    }

    /**
     * Sets the value of the salesValueToGetCheque property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSalesValueToGetCheque(Float value) {
        this.salesValueToGetCheque = value;
    }

    /**
     * Gets the value of the pointsToGetCheque property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPointsToGetCheque() {
        return pointsToGetCheque;
    }

    /**
     * Sets the value of the pointsToGetCheque property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPointsToGetCheque(BigDecimal value) {
        this.pointsToGetCheque = value;
    }

    /**
     * Gets the value of the lastAccrualTxnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastAccrualTxnDate() {
        return lastAccrualTxnDate;
    }

    /**
     * Sets the value of the lastAccrualTxnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastAccrualTxnDate(String value) {
        this.lastAccrualTxnDate = value;
    }

    /**
     * Gets the value of the pareto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPareto() {
        return pareto;
    }

    /**
     * Sets the value of the pareto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPareto(String value) {
        this.pareto = value;
    }

    /**
     * Gets the value of the paretoTendency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParetoTendency() {
        return paretoTendency;
    }

    /**
     * Sets the value of the paretoTendency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParetoTendency(String value) {
        this.paretoTendency = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType(String value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the lastTxnDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTxnDate() {
        return lastTxnDate;
    }

    /**
     * Sets the value of the lastTxnDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTxnDate(String value) {
        this.lastTxnDate = value;
    }

    /**
     * Gets the value of the lastRedemptionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastRedemptionDate() {
        return lastRedemptionDate;
    }

    /**
     * Sets the value of the lastRedemptionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastRedemptionDate(String value) {
        this.lastRedemptionDate = value;
    }

    /**
     * Gets the value of the childNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildNum() {
        return childNum;
    }

    /**
     * Sets the value of the childNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildNum(String value) {
        this.childNum = value;
    }

    /**
     * Gets the value of the personalIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalIncome() {
        return personalIncome;
    }

    /**
     * Sets the value of the personalIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalIncome(String value) {
        this.personalIncome = value;
    }

    /**
     * Gets the value of the householdIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHouseholdIncome() {
        return householdIncome;
    }

    /**
     * Sets the value of the householdIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHouseholdIncome(String value) {
        this.householdIncome = value;
    }

    /**
     * Gets the value of the passportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * Sets the value of the passportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportNumber(String value) {
        this.passportNumber = value;
    }

    /**
     * Gets the value of the otherLanguageLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLanguageLastName() {
        return otherLanguageLastName;
    }

    /**
     * Sets the value of the otherLanguageLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLanguageLastName(String value) {
        this.otherLanguageLastName = value;
    }

    /**
     * Gets the value of the otherLanguageFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLanguageFirstName() {
        return otherLanguageFirstName;
    }

    /**
     * Sets the value of the otherLanguageFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLanguageFirstName(String value) {
        this.otherLanguageFirstName = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducation(String value) {
        this.education = value;
    }

    /**
     * Gets the value of the occupation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupation() {
        return occupation;
    }

    /**
     * Sets the value of the occupation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupation(String value) {
        this.occupation = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRace(String value) {
        this.race = value;
    }

    /**
     * Gets the value of the prefCommMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefCommMethod() {
        return prefCommMethod;
    }

    /**
     * Sets the value of the prefCommMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefCommMethod(String value) {
        this.prefCommMethod = value;
    }

    /**
     * Gets the value of the memberStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberStatus() {
        return memberStatus;
    }

    /**
     * Sets the value of the memberStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberStatus(String value) {
        this.memberStatus = value;
    }

    /**
     * Gets the value of the memberSubStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberSubStatus() {
        return memberSubStatus;
    }

    /**
     * Sets the value of the memberSubStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberSubStatus(String value) {
        this.memberSubStatus = value;
    }

    /**
     * Gets the value of the cardStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardStatus() {
        return cardStatus;
    }

    /**
     * Sets the value of the cardStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardStatus(String value) {
        this.cardStatus = value;
    }

    /**
     * Gets the value of the receivePartnerPromotionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceivePartnerPromotionFlag() {
        return receivePartnerPromotionFlag;
    }

    /**
     * Sets the value of the receivePartnerPromotionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceivePartnerPromotionFlag(String value) {
        this.receivePartnerPromotionFlag = value;
    }

    /**
     * Gets the value of the segments property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentsType }
     *     
     */
    public SegmentsType getSegments() {
        return segments;
    }

    /**
     * Sets the value of the segments property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentsType }
     *     
     */
    public void setSegments(SegmentsType value) {
        this.segments = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the children property.
     * 
     * @return
     *     possible object is
     *     {@link ChildrenType }
     *     
     */
    public ChildrenType getChildren() {
        return children;
    }

    /**
     * Sets the value of the children property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChildrenType }
     *     
     */
    public void setChildren(ChildrenType value) {
        this.children = value;
    }

}
