//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 04:54:07 PM GMT+08:00 
//


package com.hybris.fortress.gensrc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FtrCustomerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FtrCustomerType">
 *   &lt;complexContent>
 *     &lt;extension base="{}CustomerType">
 *       &lt;sequence>
 *         &lt;element name="EmailVerificationFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="EShopperFTRFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="NewsletterSubscriberFTRFlag" type="{}BooleanType" minOccurs="0"/>
 *         &lt;element name="MemberPhase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastTierChgAmt" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Contact" type="{}ContactType" minOccurs="0"/>
 *         &lt;element name="Accounts" type="{}AccountsType" minOccurs="0"/>
 *         &lt;element name="TierStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TierEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ConAttribs" type="{}ConAttribsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FtrCustomerType", propOrder = {
    "emailVerificationFlag",
    "eShopperFTRFlag",
    "newsletterSubscriberFTRFlag",
    "memberPhase",
    "lastTierChgAmt",
    "contact",
    "accounts",
    "tierStartDate",
    "tierEndDate",
    "conAttribs"
})
public class FtrCustomerType
    extends CustomerType
{

    @XmlElement(name = "EmailVerificationFlag")
    protected String emailVerificationFlag;
    @XmlElement(name = "EShopperFTRFlag")
    protected String eShopperFTRFlag;
    @XmlElement(name = "NewsletterSubscriberFTRFlag")
    protected String newsletterSubscriberFTRFlag;
    @XmlElement(name = "MemberPhase")
    protected String memberPhase;
    @XmlElement(name = "LastTierChgAmt")
    protected Double lastTierChgAmt;
    @XmlElement(name = "Contact")
    protected ContactType contact;
    @XmlElement(name = "Accounts")
    protected AccountsType accounts;
    @XmlElement(name = "TierStartDate")
    protected String tierStartDate;
    @XmlElement(name = "TierEndDate")
    protected String tierEndDate;
    @XmlElement(name = "ConAttribs")
    protected ConAttribsType conAttribs;

    /**
     * Gets the value of the emailVerificationFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailVerificationFlag() {
        return emailVerificationFlag;
    }

    /**
     * Sets the value of the emailVerificationFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailVerificationFlag(String value) {
        this.emailVerificationFlag = value;
    }

    /**
     * Gets the value of the eShopperFTRFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEShopperFTRFlag() {
        return eShopperFTRFlag;
    }

    /**
     * Sets the value of the eShopperFTRFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEShopperFTRFlag(String value) {
        this.eShopperFTRFlag = value;
    }

    /**
     * Gets the value of the newsletterSubscriberFTRFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsletterSubscriberFTRFlag() {
        return newsletterSubscriberFTRFlag;
    }

    /**
     * Sets the value of the newsletterSubscriberFTRFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsletterSubscriberFTRFlag(String value) {
        this.newsletterSubscriberFTRFlag = value;
    }

    /**
     * Gets the value of the memberPhase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberPhase() {
        return memberPhase;
    }

    /**
     * Sets the value of the memberPhase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberPhase(String value) {
        this.memberPhase = value;
    }

    /**
     * Gets the value of the lastTierChgAmt property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLastTierChgAmt() {
        return lastTierChgAmt;
    }

    /**
     * Sets the value of the lastTierChgAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLastTierChgAmt(Double value) {
        this.lastTierChgAmt = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link ContactType }
     *     
     */
    public ContactType getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactType }
     *     
     */
    public void setContact(ContactType value) {
        this.contact = value;
    }

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link AccountsType }
     *     
     */
    public AccountsType getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountsType }
     *     
     */
    public void setAccounts(AccountsType value) {
        this.accounts = value;
    }

    /**
     * Gets the value of the tierStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTierStartDate() {
        return tierStartDate;
    }

    /**
     * Sets the value of the tierStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTierStartDate(String value) {
        this.tierStartDate = value;
    }

    /**
     * Gets the value of the tierEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTierEndDate() {
        return tierEndDate;
    }

    /**
     * Sets the value of the tierEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTierEndDate(String value) {
        this.tierEndDate = value;
    }

    /**
     * Gets the value of the conAttribs property.
     * 
     * @return
     *     possible object is
     *     {@link ConAttribsType }
     *     
     */
    public ConAttribsType getConAttribs() {
        return conAttribs;
    }

    /**
     * Sets the value of the conAttribs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConAttribsType }
     *     
     */
    public void setConAttribs(ConAttribsType value) {
        this.conAttribs = value;
    }

}
